openapi: 3.0.3

info:
  title: 'LevelUp Platform API: Parameters'
  description: Common parameters shared across microservices.
  version: '1.0'
  contact:
    name: Dmitry Khodakovsky
    email: khda91@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths: {}

components:
  parameters:
    limit:
      description: Standard pagination parameter. Defines the maximum number of entries returned in the response.
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        default: 10
        example: 25
    offset:
      description: Standard pagination parameter. Defines the number of entries to skip before beginning to return the search results.
      name: offset
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
        example: 10
