openapi: 3.0.3

info:
  title: 'LevelUp Platform API: Common types'
  description: Common data types shared across microservices.
  version: '1.0'
  contact:
    name: Dmitry Khodakovsky
    email: khda91@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths: {}

components:
  schemas:
    PaginationData:
      description: Describes the pagination information for the provided results.
      type: object
      properties:
        limit:
          description: Inbound pagination parameter. Defines the maximum number of entries returned in the response.
          type: integer
          format: int32
          minimum: 1
          example: 25
        offset:
          description: Inbound pagination parameter. Defines the number of entries to skip before beginning to return the search results.
          type: integer
          format: int32
          minimum: 0
          example: 10
        totalCount:
          description: Total number of results found for the request.
          type: integer
          format: int32
          minimum: 0
          example: 252

    ViolationData:
      description: Results of a validation constraint violation produced by some request.
      type: object
      properties:
        code:
          description: Unique identifier of the type of the validation problem.
          type: string
          maxLength: 255
          example: 'PA1234'
        field:
          description: Reference to the field that did not pass the validation.
          type: string
          maxLength: 255
          example: 'PersonData.email'
        detail:
          description: Human-readable explanation of the validation problem.
          type: string
          maxLength: 65535
          example: 'Your current balance is 30, but that costs 50.'
      required:
        - code

    ProblemResponse:
      description: Problem details serialized according to RFC 7807.
      type: object
      properties:
        type:
          description: Problem type.
          type: string
          maxLength: 2048
          example: 'Errors#Validation'
        title:
          description: Short, human-readable summary of the problem type.
          type: string
          maxLength: 255
          example: 'You do not have enough credit'
        status:
          description: The HTTP status code generated by the origin server.
          type: string
          pattern: ^[0-9]{3}$
          example: 500
        detail:
          description: Human-readable explanation specific to this occurrence of the problem.
          type: string
          maxLength: 65535
          example: 'Your current balance is 30, but that costs 50.'
        violations:
          description: Validation constraints violated by the request.
          type: array
          items:
            $ref: '#/components/schemas/ViolationData'
      required:
        - type
        - title
        - status
        - detail
